## Bowling Game

In [86]:
def lets_bowl():
    
    # Importing some useful tools. We'll display our final score
    # in a Pandas DataFrame.
    import numpy as np
    import pandas as pd
    
    # We'll start, of course, in the first frame.
    frame = 1
    
    # Our scoresheet will have scores for each ball as well as
    # a running cumulative score.
    score = np.zeros((4, 10), dtype=object)
    
    # Since the tenth frame can have extra balls, we'll treat that
    # frame separately.
    while frame < 10:
        
        # First ball score
        print(f"How many pins did you knock down on your first ball in frame {frame}?")
        first = int(input("Please enter a number from 0 to 10: "))
        
        # If we bowl a strike
        if first == 10:
            
            print("Strike!")
            
            # Record the strike as such and store the 10-pin score
            score[0, frame-1] = 'X'
            
            score[1, frame-1] = '-'
            
            score[2, frame-1] = 10
        
        # But in the general case:
        else:
            
            # Zeroes are generally marked specially as well
            if first == 0:
            
                score[0, frame-1] = '-'
            
            # Score the first ball
            else:
                
                score[0, frame-1] = first
            
            # If we don't get a strike, we have a second ball to score
            print("How many pins did you knock down on your second ball?")
            second = int(input(f"Please enter a number from 0 to {10-first}: "))

            # If we bowl a spare
            if second == 10 - first:
                
                print("Spare!")
                
                # Record the spare as such and store the 10-pin score
                score[1, frame-1] = '/'
                
                score[2, frame-1] = 10
            
            # But in the general case:
            else:
                
                # Again, mark the zeroes specially
                if second == 0:
            
                    score[1, frame-1] = '-'
                
                # Score the second ball
                else:
                    
                    score[1, frame-1] = second
                
                score[2, frame-1] = first + second
        
        # Update the cumulative score
        # If we're beyond the first frame, then take the previous
        # value of the cumulative score and add the current frame's
        # score.
        if frame > 1:
            
            score[3, frame-1] = score[2, frame-1] + score[3, frame-2]
        
        # Otherwise just set the cumulative score to the first frame's
        # score.
        else:
            
            score[3, frame-1] = score[2, frame-1]
        
        # A strike in frame F gets the next two rolls added into F's score.
        # A spare in frame F gets the next roll added into F's score.
        
        if frame > 1:
        
            if score[0, frame-2] == 'X' or score[1, frame-2] == '/':
        
                # Add ten for any strike in the current frame
                if score[0, frame-1] == 'X':

                    score[2, frame-2] += 10

                # Otherwise just add the value of the first ball.
                elif type(score[0, frame-1]) == int:

                    score[2, frame-2] += score[0, frame-1]
        
            # Then, if we got a strike in the last frame,
            # add the value of the second ball in the current frame (if
            # the first ball was not a strike).
            if score[0, frame-2] == 'X':

                if score[1, frame-1] == '/':

                    score[2, frame-2] += 10 - score[0, frame-1]

                elif type(score[1, frame-1]) == int:

                    score[2, frame-2] += score[1, frame-1]
            
        if frame > 2:
    
            # If we got a strike in each of the last two frames:
            if score[0, frame-3] == 'X' and score[0, frame-2] == 'X':

                if score[0, frame-1] == 'X':
                    
                    score[2, frame-3] += 10
                    
                    score[3, frame-3] += 10

                elif type(score[0, frame-1]) == int:
                    
                    score[2, frame-3] += score[0, frame-1]
                    
                    score[3, frame-3] += score[0, frame-1]
        
        # Update the cumulative scores
        score[3, frame-2] = score[2, frame-2] + score[3, frame-3]
        
        score[3, frame-1] = score[2, frame-1] + score[3, frame-2]
        
        frame += 1
        
    # Tenth frame
    print("How many pins did you knock down on your first ball in frame 10?")
    first = int(input("Please enter a number from 0 to 10: "))

    if first == 10:
        print("Strike!")

        # Record the strike as such and store the 10-pin score
        score[0, 9] = 'X'
        
        score[1, 9] = ['-', '-']
        
        score[2, 9] = 10

    else:

        if first == 0:

            score[0, 9] = '-'

        else:
            
            score[0, 9] = first

        print("How many pins did you knock down on your second ball?")
        second = int(input(f"Please enter a number from 0 to {10-first}: "))

        if second == 10 - first:

            print("Spare!")
            
            # Record the spare as such and store the 10-pin score
            score[1, 9] = ['/', '-']
            
            score[2, 9] = 10

        else:

            if second == 0:

                score[1, 9] = ['-', '-']

            else:
                
                score[1, 9] = second

            score[2, 9] = first + second
    
    score[3, 9] = score[2, 9] + score[3, 8]
    
    # If we bowl a strike in the tenth frame, then we get two bonus balls.
    if score[0, 9] == 'X':

        print("How many pins did you knock down on your first bonus ball?")
        bonus1 = int(input("Please enter a number from 0 to 10: "))

        if bonus1 == 10:
            
            score[1, 9] = ['X', '-']
            
        else:
        
            score[1, 9] = [bonus1, '-']
        
        score[2, 9] += bonus1

        if score[1, 9][0] == 'X':
        
            print("How many pins did you knock down on your second bonus ball?")
            bonus2 = int(input("Please enter a number from 0 to 10: "))
            
        else:
            
            print("How many pins did you knock down on your second bonus ball?")
            bonus2 = int(input(f"Please enter a number from 0 to {10-bonus1}: "))
   
        if bonus2 == 10:
            
            score[1, 9][1] = 'X'
            
        elif bonus2 == 0:
            
            score[1, 9][1] = '-'
        
        else:
            
            score[1, 9][1] = bonus2
        
        score[2, 9] += bonus2
    
    # If we bowl a spare in the tenth frame, then we get one bonus ball.
    if score[1, 9] == ['/', '-']:
        
        print("How many pins did you knock down on your bonus ball?")
        bonus1 = int(input("Please enter a number from 0 to 10: "))
        
        if bonus1 == 10:
            
            score[1, 9] = ['/', 'X']
            
        else:

            score[1, 9][1] = 10 - score[0, 9] + bonus1
        
        score[2, 9] += bonus1
        
    # Adjusting eighth- and ninth-frame scores if necessary
    
    # If we got a strike or a spare in the ninth frame:
    if score[0, 8] == 'X' or score[1, 8] == '/':
        
        # Add ten for any strike in the tenth
        if score[0, 9] == 'X':
            
            score[2, 8] += 10
            
        # Otherwise just add the value of the first ball in the tenth.
        elif type(score[0, 9]) == int:
            
            score[2, 8] += score[0, 9]
        
        # Then, if we got a strike in the ninth,
        # add the value of the second ball in the tenth.
        if score[0, 8] == 'X':
            
            if type(score[1, 9]) == int:

                score[2, 8] += score[1, 9]

            elif score[1, 9][0] == 'X':

                score[2, 8] += 10

            elif type(score[1, 9][0]) == int:

                score[2, 8] += score[1, 9][0]
            
        score[3, 8] = score[2, 8] + score[3, 7]
            
    # If we got a strike in the eighth and a strike in the ninth
    if score[0, 7] == 'X' and score[0, 8] == 'X':
        
        score[2, 7] += 10
        
        score[3, 7] += 10
        
    score[3, 8] = score[2, 8] + score[3, 7]
        
    score[3, 9] = score[2, 9] + score[3, 8]
        
    return pd.DataFrame(score, columns=range(1, 11),
                        index=['first_ball', 'second_ball', 'frame_score', 'cumulative_score'])

In [74]:
lets_bowl()

How many pins did you knock down on your first ball in frame 1?
Please enter a number from 0 to 10: 9
How many pins did you knock down on your second ball?
Please enter a number from 0 to 1: 0
How many pins did you knock down on your first ball in frame 2?
Please enter a number from 0 to 10: 9
How many pins did you knock down on your second ball?
Please enter a number from 0 to 1: 0
How many pins did you knock down on your first ball in frame 3?
Please enter a number from 0 to 10: 9
How many pins did you knock down on your second ball?
Please enter a number from 0 to 1: 0
How many pins did you knock down on your first ball in frame 4?
Please enter a number from 0 to 10: 9
How many pins did you knock down on your second ball?
Please enter a number from 0 to 1: 0
How many pins did you knock down on your first ball in frame 5?
Please enter a number from 0 to 10: 9
How many pins did you knock down on your second ball?
Please enter a number from 0 to 1: 0
How many pins did you knock down on your first ball in frame 6?
Please enter a number from 0 to 10: 9
How many pins did you knock down on your second ball?
Please enter a number from 0 to 1: 0
How many pins did you knock down on your first ball in frame 7?
Please enter a number from 0 to 10: 9
How many pins did you knock down on your second ball?
Please enter a number from 0 to 1: 0
How many pins did you knock down on your first ball in frame 8?
Please enter a number from 0 to 10: 9
How many pins did you knock down on your second ball?
Please enter a number from 0 to 1: 0
How many pins did you knock down on your first ball in frame 9?
Please enter a number from 0 to 10: 9
How many pins did you knock down on your second ball?
Please enter a number from 0 to 1: 0
How many pins did you knock down on your first ball in frame 10?
Please enter a number from 0 to 10: 9
How many pins did you knock down on your second ball?
Please enter a number from 0 to 1: 0

                 1   2   3   4   5   6   7   8   9   10
first_ball        9   9   9   9   9   9   9   9   9   9
second_ball       -   -   -   -   -   -   -   -   -   0
frame_score       9   9   9   9   9   9   9   9   9   9
cumulative_score  9  18  27  36  45  54  63  72  81  90

In [80]:
lets_bowl()

How many pins did you knock down on your first ball in frame 1?
Please enter a number from 0 to 10: 10
Strike!
How many pins did you knock down on your first ball in frame 2?
Please enter a number from 0 to 10: 10
Strike!
How many pins did you knock down on your first ball in frame 3?
Please enter a number from 0 to 10: 10
Strike!
How many pins did you knock down on your first ball in frame 4?
Please enter a number from 0 to 10: 10
Strike!
How many pins did you knock down on your first ball in frame 5?
Please enter a number from 0 to 10: 10
Strike!
How many pins did you knock down on your first ball in frame 6?
Please enter a number from 0 to 10: 10
Strike!
How many pins did you knock down on your first ball in frame 7?
Please enter a number from 0 to 10: 10
Strike!
How many pins did you knock down on your first ball in frame 8?
Please enter a number from 0 to 10: 10
Strike!
How many pins did you knock down on your first ball in frame 9?
Please enter a number from 0 to 10: 10
Strike!
How many pins did you knock down on your first ball in frame 10?
Please enter a number from 0 to 10: 10
Strike!
How many pins did you knock down on your first bonus ball?
Please enter a number from 0 to 10: 10
How many pins did you knock down on your second bonus ball?
Please enter a number from 0 to 10: 10

                  1   2   3    4    5    6    7    8    9       10
first_ball         X   X   X    X    X    X    X    X    X       X
second_ball        -   -   -    -    -    -    -    -    -  [X, X]
frame_score       30  30  30   30   30   30   30   30   30      30
cumulative_score  30  60  90  120  150  180  210  240  270     300

In [85]:
lets_bowl()

How many pins did you knock down on your first ball in frame 1?
Please enter a number from 0 to 10: 9
How many pins did you knock down on your second ball?
Please enter a number from 0 to 1: 0
How many pins did you knock down on your first ball in frame 2?
Please enter a number from 0 to 10: 10
Strike!
How many pins did you knock down on your first ball in frame 3?
Please enter a number from 0 to 10: 10
Strike!
How many pins did you knock down on your first ball in frame 4?
Please enter a number from 0 to 10: 10
Strike!
How many pins did you knock down on your first ball in frame 5?
Please enter a number from 0 to 10: 5
How many pins did you knock down on your second ball?
Please enter a number from 0 to 5: 5
Spare!
How many pins did you knock down on your first ball in frame 6?
Please enter a number from 0 to 10: 0
How many pins did you knock down on your second ball?
Please enter a number from 0 to 10: 9
How many pins did you knock down on your first ball in frame 7?
Please enter a number from 0 to 10: 10
Strike!
How many pins did you knock down on your first ball in frame 8?
Please enter a number from 0 to 10: 9
How many pins did you knock down on your second ball?
Please enter a number from 0 to 1: 1
Spare!
How many pins did you knock down on your first ball in frame 9?
Please enter a number from 0 to 10: 3
How many pins did you knock down on your second ball?
Please enter a number from 0 to 7: 7
Spare!
How many pins did you knock down on your first ball in frame 10?
Please enter a number from 0 to 10: 5
How many pins did you knock down on your second ball?
Please enter a number from 0 to 5: 5
Spare!
How many pins did you knock down on your bonus ball?
Please enter a number from 0 to 10: 10

                 1   2   3   4   5    6    7    8    9       10
first_ball        9   X   X   X   5    -    X    9    3       5
second_ball       -   -   -   -   /    9    -    /    /  [/, X]
frame_score       9  30  25  20  10    9   20   13   15      20
cumulative_score  9  39  64  84  94  103  123  136  151     171

9, 0; 10; 10; 10; 5, 5; 0, 9; 10; 9, 1; 3, 7; 5, 5, 10

9; 39; 64; 84; 94; 103; 123; 136; 151; 171

In [87]:
from bowling import lets_bowl

In [ ]:
lets_bowl()

Frame | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10
--- | --- | --- | --- | --- | --- | --- | --- | --- | --- | ---
first ball | 9 | X | X | X | 5 | - | X | 9 | 3 | 5
second ball | - | - | - | - | / | 9 | - | / | / | \[/, X\]
frame score | 9 | 30 | 25 | 20 | 10 | 9 | 20 | 13 | 15 | 20
cumulative score | 9 | 39 | 64 | 84 | 94 | 103 | 123 | 136 | 151 | 171

## Countries' Extreme Points

### Northernmost and Southernmost Points

In [85]:
x_lats = {}

x_lats['Canada'] = {'n': 83.1, 's': 41 + 41/60, 'mn': 72, 'ms': 41 + 19/20}
x_lats['Russia'] = {'n': 81 + 51/60, 's': 41 + 11/60, 'mn': 77 + 43/60, 'ms': 41 + 11/60}
x_lats['Norway'] = {'n': 80 + 49/60, 's': 57 + 19/20, 'mn': 71 + 2/15, 'ms': 58}
x_lats['United States'] = {'n': 71 + 23/60, 's': -14 - 17/30, 'mn': 71 + 23/60, 'ms': 25 + 7/60}
x_lats['Finland'] = {'n': 70 + 1/12, 's': 59.5, 'mn': 70 + 1/12, 'ms': 59.8}
x_lats['Sweden'] = {'n': 69 + 1/15, 's': 55 + 1/3, 'mn': 69 + 1/15, 'ms': 55 + 1/3}
x_lats['Iceland'] = {'n': 67 + 2/15, 's': 63 + 17/60, 'mn': 66 + 8/15, 'ms': 63 + 23/60}
x_lats['United Kingdom'] = {'n': 60 + 17/20, 's': -52 - 53/60, 'mn': 58 + 2/3, 'ms': 49 + 19/20}
x_lats['Estonia'] = {'n': 59 + 4/5, 's': 57 + 31/60, 'mn': 59 + 2/3, 'ms': 57 + 31/60}
x_lats['Latvia'] = {'n': 58 + 1/12, 's': 55 + 2/3, 'mn': 58 + 1/12, 'ms': 55 + 2/3}

x_lats['Denmark'] = {'n': 83 + 2/3, 's': 54 + 17/30, 'mn': 57 + 3/4, 'ms': 54 + 17/30}
x_lats['Lithuania'] = {'n': 56 + 9/20, 's': 53.9, 'mn': 56 + 9/20, 'ms': 53.9}
x_lats['Belarus'] = {'n': 56 + 2/15, 's': 51.25, 'mn': 56 + 2/15, 'ms': 51.25}
x_lats['Kazakhstan'] = {'n': 55 + 43/60, 's': 40 + 17/30, 'mn': 55 + 43/60, 'ms': 40 + 17/30}
x_lats['Ireland'] = {'n': 55 + 13/30, 's': 51 + 23/60, 'mn': 55 + 23/60, 'ms': 51 + 13/30}
x_lats['Germany'] = {'n': 55 + 1/20, 's': 47 + 17/60, 'mn': 54.9, 'ms': 47 + 17/60}
x_lats['Poland'] = {'n': 54 + 5/6, 's': 49, 'mn': 54 + 5/6, 'ms': 49}
x_lats['China'] = {'n': 53 + 17/30, 's': 20 + 7/30, 'mn': 53 + 17/30, 'ms': 20 + 7/30}
x_lats['Netherlands'] = {'n': 53 + 8/15, 's': 11 + 59/60, 'mn': 53 + 9/20, 'ms': 50.75}
x_lats['Ukraine'] = {'n': 52 + 11/30, 's': 44 + 23/60, 'mn': 52 + 11/30, 'ms': 44 + 23/60}

x_lats['Mongolia'] = {'n': 52 + 3/20, 's': 41 + 17/30, 'mn': 52 + 3/20, 'ms': 41 + 17/30}
x_lats['Belgium'] = {'n': 51.5, 's': 49.5, 'mn': 51.5, 'ms': 49.5}
x_lats['France'] = {'n': 51 + 1/12, 's': -27 - 11/12, 'mn': 51 + 1/12, 'ms': 42 + 1/3}
x_lats['Czechia'] = {'n': 51 + 1/30, 's': 48 + 11/20, 'mn': 51 + 1/30, 'ms': 48 + 11/20}
x_lats['Luxembourg'] = {'n': 50 + 11/60, 's': 49 + 9/20, 'mn': 50 + 11/60, 'ms': 49 + 9/20}
x_lats['Slovakia'] = {'n': 49.6, 's': 47 + 11/15, 'mn': 49.6, 'ms': 47 + 11/15}
x_lats['Austria'] = {'n': 49 + 1/60, 's': 46 + 23/60, 'mn': 49 + 1/60, 'ms': 46 + 23/60}
x_lats['Hungary'] = {'n': 48 + 7/12, 's': 45.75, 'mn': 48 + 7/12, 'ms': 45.75}
x_lats['Moldova'] = {'n': 48 + 7/15, 's': 45 + 7/15, 'mn': 48 + 7/15, 'ms': 45 + 7/15}
x_lats['Romania'] = {'n': 48.25, 's': 43 + 19/30, 'mn': 48.25, 'ms': 43 + 19/30}

x_lats['Switzerland'] = {'n': 47.8, 's': 45 + 5/6, 'mn': 47.8, 'ms': 45 + 5/6}
x_lats['Liechtenstein'] = {'n': 47 + 7/30, 's': 47 + 1/20, 'mn': 47 + 7/30, 'ms': 47 + 1/20}
x_lats['Italy'] = {'n': 47 + 1/12, 's': 35.5, 'mn': 47 + 1/12, 'ms': 37 + 14/15}
x_lats['Slovenia'] = {'n': 46 + 13/15, 's': 45 + 5/12, 'mn': 46 + 13/15, 'ms': 45 + 5/12}
x_lats['Croatia'] = {'n': 46 + 11/20, 's': 42 + 23/60, 'mn': 46 + 11/20, 'ms': 42 + 23/60}
x_lats['Serbia'] = {'n': 46 + 11/60, 's': 42 + 13/60, 'mn': 46 + 11/60, 'ms': 42 + 13/60}
x_lats['Uzbekistan'] = {'n': 45.6, 's': 37 + 11/60, 'mn': 45.6, 'ms': 37 + 11/60}
x_lats['Japan'] = {'n': 45 + 11/20, 's': 20 + 5/12, 'mn': 45 + 11/20, 'ms': 20 + 5/12}
x_lats['Bosnia and Herzegovina'] = {'n': 45 + 4/15, 's': 42 + 17/30, 'mn': 45 + 4/15, 'ms': 42 + 17/30}
x_lats['Bulgaria'] = {'n': 44 + 13/60, 's': 41.25, 'mn': 44 + 13/60, 'ms': 41.25}

x_lats['San Marino'] = {'n': 43 + 59/60, 's': 43.9, 'mn': 43 + 59/60, 'ms': 43.9}
x_lats['Spain'] = {'n': 43 + 47/60, 's': 27 + 19/30, 'mn': 43 + 47/60, 'ms': 36}
x_lats['Monaco'] = {'n': 43.75, 's': 43 + 11/15, 'mn': 43.75, 'ms': 43 + 11/15}
x_lats['Georgia'] = {'n': 43 + 7/12, 's': 41 + 1/20, 'mn': 43 + 7/12, 'ms': 41 + 1/20}
x_lats['Montenegro'] = {'n': 43 + 8/15, 's': 41 + 17/20, 'mn': 43 + 8/15, 'ms': 41 + 17/20}
x_lats['Kyrgyzstan'] = {'n': 43 + 4/15, 's': 39 + 1/6, 'mn': 43 + 4/15, 'ms': 39 + 1/6}
x_lats['North Korea'] = {'n': 43, 's': 37 + 2/3, 'mn': 43, 'ms': 37 + 2/3}
x_lats['Turkmenistan'] = {'n': 42 + 5/6, 's': 35 + 3/20, 'mn': 42 + 5/6, 'ms': 35 + 3/20}
x_lats['Andorra'] = {'n': 42 + 13/20, 's': 42 + 13/30, 'mn': 42 + 13/20, 'ms': 42 + 13/30}
x_lats['Albania'] = {'n': 42.5, 's': 39 + 13/20, 'mn': 42.5, 'ms': 39 + 13/20}

In [86]:
x_lats['North Macedonia'] = {'n': 42 + 7/20, 's': 40 + 13/15, 'mn': 42 + 7/20, 'ms': 40 + 13/15}
x_lats['Portugal'] = {'n': 42 + 7/60, 's': 30 + 1/20, 'mn': 42 + 7/60, 'ms': 36 + 19/20}
x_lats['Turkiye'] = {'n': 42.1, 's': 35 + 49/60, 'mn': 42.1, 'ms': 35 + 49/60}
x_lats['Vatican City'] = {'n': 41.9, 's': 41.9, 'mn': 41.9, 'ms': 41.9}
x_lats['Azerbaijan'] = {'n': 41 + 53/60, 's': 38.4, 'mn': 41 + 53/60, 'ms': 38.4}
x_lats['Greece'] = {'n': 41 + 43/60, 's': 34 + 49/60, 'mn': 41 + 43/60, 'ms': 36 + 23/60}
x_lats['Armenia'] = {'n': 41 + 17/60, 's': 38 + 5/6, 'mn': 41 + 17/60, 'ms': 38 + 5/6}
x_lats['Tajikistan'] = {'n': 41 + 1/30, 's': 36 + 2/3, 'mn': 41 + 1/30, 'ms': 36 + 2/3}
x_lats['Iran'] = {'n': 39 + 47/60, 's': 25 + 1/15, 'mn': 39 + 47/60, 'ms': 25 + 1/15}
x_lats['South Korea'] = {'n': 38.6, 's': 33.1, 'mn': 38.6, 'ms': 34 + 17/60}

x_lats['Afghanistan'] = {'n': 38 + 11/30, 's': 29 + 23/60, 'mn': 38 + 11/30, 'ms': 29 + 23/60}
x_lats['Tunisia'] = {'n': 37 + 31/60, 's': 30.25, 'mn': 37 + 7/20, 'ms': 30.25}
x_lats['Iraq'] = {'n': 37 + 23/60, 's': 29 + 1/15, 'mn': 37 + 23/60, 'ms': 29 + 1/15}
x_lats['Syria'] = {'n': 37 + 19/60, 's': 32 + 19/60, 'mn': 37 + 19/60, 'ms': 32 + 19/60}
x_lats['Pakistan'] = {'n': 37 + 2/15, 's': 23.7, 'mn': 37 + 2/15, 'ms': 23.7}
x_lats['India'] = {'n': 37.1, 's': 6 + 11/15, 'mn': 37.1, 'ms': 8.1}
x_lats['Algeria'] = {'n': 37 + 1/12, 's': 18 + 29/30, 'mn': 37 + 1/12, 'ms': 18 + 29/30}
x_lats['Malta'] = {'n': 36 + 1/12, 's': 35 + 47/60, 'mn': 36 + 1/12, 'ms': 35 + 47/60}
x_lats['Morocco'] = {'n': 35 + 11/12, 's': 27 + 2/3, 'mn': 35 + 11/12, 'ms': 27 + 2/3}
x_lats['Cyprus'] = {'n': 35.7, 's': 34 + 11/20, 'mn': 35.7, 'ms': 34 + 11/20}

x_lats['Lebanon'] = {'n': 34 + 43/60, 's': 33 + 1/20, 'mn': 34 + 43/60, 'ms': 33 + 1/20}
x_lats['Jordan'] = {'n': 33 + 11/30, 's': 29 + 11/60, 'mn': 33 + 11/30, 'ms': 29 + 11/60}
x_lats['Israel'] = {'n': 33 + 17/60, 's': 29.5, 'mn': 33 + 17/60, 'ms': 29.5}
x_lats['Libya'] = {'n': 33 + 1/6, 's': 19.5, 'mn': 33 + 1/6, 'ms': 19.5}
x_lats['Mexico'] = {'n': 32 + 43/60, 's': 14 + 8/15, 'mn': 32 + 43/60, 'ms': 14 + 8/15}
x_lats['Palestine'] = {'n': 32 + 8/15, 's': 31 + 13/60, 'mn': 32 + 8/15, 'ms': 31 + 13/60}
x_lats['Saudi Arabia'] = {'n': 32 + 7/30, 's': 16 + 23/60, 'mn': 32 + 7/30, 'ms': 16 + 23/60}
x_lats['Egypt'] = {'n': 31.6, 's': 22, 'mn': 31.6, 'ms': 22}
x_lats['Nepal'] = {'n': 30 + 13/30, 's': 26 + 11/30, 'mn': 30 + 13/30, 'ms': 26 + 11/30}
x_lats['Kuwait'] = {'n': 30.1, 's': 28 + 8/15, 'mn': 30.1, 'ms': 28 + 8/15}

x_lats['Myanmar'] = {'n': 28 + 8/15, 's': 9.6, 'mn': 28 + 8/15, 'ms': 9 + 59/60}
x_lats['Bhutan'] = {'n': 28 + 1/3, 's': 26 + 43/60, 'mn': 28 + 1/3, 'ms': 26 + 43/60}
x_lats['Mauritania'] = {'n': 27 + 19/60, 's': 14 + 43/60, 'mn': 27 + 19/60, 'ms': 14 + 43/60}
x_lats['Bahamas'] = {'n': 27 + 4/15, 's': 20 + 11/12, 'mn': 27 + 4/15, 'ms': 20 + 11/12}
x_lats['Bangladesh'] = {'n': 26 + 19/30, 's': 20 + 7/12, 'mn': 26 + 19/30, 'ms': 20.75}
x_lats['Oman'] = {'n': 26.5, 's': 16 + 13/20, 'mn': 26.5, 'ms': 16 + 13/20}
x_lats['Taiwan'] = {'n': 26 + 23/60, 's': 21 + 53/60, 'mn': 26 + 23/60, 'ms': 21 + 53/60}
x_lats['Bahrain'] = {'n': 26 + 17/60, 's': 25 + 17/30, 'mn': 26 + 17/60, 'ms': 25 + 17/30}
x_lats['Qatar'] = {'n': 26 + 3/20, 's': 24 + 7/15, 'mn': 26 + 3/20, 'ms': 24 + 7/15}
x_lats['United Arab Emirates'] = {'n': 26 + 1/12, 's': 22 + 19/30, 'mn': 26 + 1/12, 'ms': 22 + 19/30}

x_lats['Mali'] = {'n': 25 + 1/15, 's': 10 + 3/20, 'mn': 25 + 1/15, 'ms': 10 + 3/20}
x_lats['Niger'] = {'n': 23 + 31/60, 's': 11.7, 'mn': 23 + 31/60, 'ms': 11.7}
x_lats['Chad'] = {'n': 23 + 29/60, 's': 7 + 9/20, 'mn': 23 + 29/60, 'ms': 7 + 9/20}
x_lats['Vietnam'] = {'n': 23 + 9/20, 's': 7 + 17/20, 'mn': 23 + 9/20, 'ms': 8 + 7/12}
x_lats['Cuba'] = {'n': 23 + 4/15, 's': 19 + 5/6, 'mn': 23 + 4/15, 'ms': 19 + 5/6}
x_lats['Laos'] = {'n': 22 + 29/60, 's': 13 + 11/12, 'mn': 22 + 29/60, 'ms': 13 + 11/12}
x_lats['Sudan'] = {'n': 22.2, 's': 8 + 41/60, 'mn': 22.2, 'ms': 8 + 41/60}
x_lats['Philippines'] = {'n': 21 + 7/60, 's': 4 + 7/12, 'mn': 21 + 7/60, 'ms': 4 + 7/12}
x_lats['Thailand'] = {'n': 20 + 9/20, 's': 5 + 37/60, 'mn': 20 + 9/20, 'ms': 5 + 37/60}
x_lats['Haiti'] = {'n': 20 + 1/15, 's': 18 + 1/60, 'mn': 20 + 1/15, 'ms': 18 + 1/60}

In [87]:
x_lats['Dominican Republic'] = {'n': 19 + 11/12, 's': 17 + 7/15, 'mn': 19 + 11/12, 'ms': 17.6}
x_lats['Yemen'] = {'n': 18 + 59/60, 's': 12.1, 'mn': 18 + 59/60, 'ms': 12.6}
x_lats['Jamaica'] = {'n': 18 + 31/60, 's': 17.7, 'mn': 18 + 31/60, 'ms': 17.7}
x_lats['Belize'] = {'n': 18 + 9/20, 's': 15 + 53/60, 'mn': 18 + 9/20, 'ms': 15 + 53/60}
x_lats['Eritrea'] = {'n': 18, 's': 12 + 11/30, 'mn': 18, 'ms': 12 + 11/30}
x_lats['Guatemala'] = {'n': 17 + 49/60, 's': 13 + 11/15, 'mn': 17 + 49/60, 'ms': 13 + 11/15}
x_lats['Antigua and Barbuda'] = {'n': 17 + 11/15, 's': 16 + 14/15, 'mn': 17 + 11/15, 'ms': 16 + 14/15}
x_lats['Saint Kitts and Nevis'] = {'n': 17 + 13/30, 's': 17.1, 'mn': 17 + 13/30, 'ms': 17.1}
x_lats['Honduras'] = {'n': 17.4, 's': 12 + 59/60, 'mn': 17.4, 'ms': 12 + 59/60}
x_lats['Cabo Verde'] = {'n': 17.2, 's': 14.8, 'mn': 17.2, 'ms': 14.8}

x_lats['Senegal'] = {'n': 16 + 41/60, 's': 12.3, 'mn': 16 + 41/60, 'ms': 12.3}
x_lats['Colombia'] = {'n': 15 + 13/15, 's': -4 - 7/30, 'mn': 12 + 9/20, 'ms': -4 - 7/30}
x_lats['Venezuela'] = {'n': 15 + 2/3, 's': 2/3, 'mn': 12 + 11/60, 'ms': 2/3}
x_lats['Dominica'] = {'n': 15 + 19/30, 's': 15.2, 'mn': 15 + 19/30, 'ms': 15.2}
x_lats['Burkina Faso'] = {'n': 15 + 1/12, 's': 9.4, 'mn': 15 + 1/12, 'ms': 9.4}
x_lats['Nicaragua'] = {'n': 15 + 1/60, 's': 10 + 43/60, 'mn': 15 + 1/60, 'ms': 10 + 43/60}
x_lats['Ethiopia'] = {'n': 14 + 53/60, 's': 3.4, 'mn': 14 + 53/60, 'ms': 3.4}
x_lats['Marshall Islands'] = {'n': 14 + 8/15, 's': 4 + 17/30, 'mn': 14 + 8/15, 'ms': 4 + 17/30}
x_lats['Cambodia'] = {'n': 14.5, 's': 9 + 11/12, 'mn': 14.5, 'ms': 10.4}
x_lats['El Salvador'] = {'n': 14 + 13/30, 's': 13 + 3/20, 'mn': 14 + 13/30, 'ms': 13 + 3/20}

x_lats['Saint Lucia'] = {'n': 14 + 7/60, 's': 13.7, 'mn': 14 + 7/60, 'ms': 13.7}
x_lats['Nigeria'] = {'n': 13 + 5/6, 's': 4 + 17/60, 'mn': 13 + 5/6, 'ms': 4 + 17/60}
x_lats['Gambia'] = {'n': 13 + 49/60, 's': 13 + 1/30, 'mn': 13 + 49/60, 'ms': 13 + 1/30}
x_lats['Saint Vincent and the Grenadines'] = {'n': 13 + 11/30, 's': 12 + 8/15, 'mn': 13 + 11/30, 'ms': 12 + 8/15}
x_lats['Barbados'] = {'n': 13 + 1/3, 's': 13 + 1/20, 'mn': 13 + 1/3, 'ms': 13 + 1/20}
x_lats['Cameroon'] = {'n': 13 + 1/12, 's': 1 + 13/20, 'mn': 13 + 1/12, 'ms': 1 + 13/20}
x_lats['Djibouti'] = {'n': 12 + 43/60, 's': 10 + 14/15, 'mn': 12 + 43/60, 'ms': 10 + 14/15}
x_lats['Guinea'] = {'n': 12.7, 's': 7.2, 'mn': 12.7, 'ms': 7.2}
x_lats['Grenada'] = {'n': 12 + 31/60, 's': 11 + 59/60, 'mn': 12 + 31/60, 'ms': 11 + 59/60}
x_lats['Benin'] = {'n': 12 + 5/12, 's': 6 + 7/30, 'mn': 12 + 5/12, 'ms': 6 + 7/30}

x_lats['South Sudan'] = {'n': 12 + 7/30, 's': 3 + 29/60, 'mn': 12 + 7/30, 'ms': 3 + 29/60}
x_lats['Somalia'] = {'n': 11 + 59/60, 's': -1 - 2/3, 'mn': 11 + 59/60, 'ms': -1 - 2/3}
x_lats['Trinidad and Tobago'] = {'n': 11 + 7/20, 's': 10 + 1/20, 'mn': 11 + 7/20, 'ms': 10 + 1/20}
x_lats['Costa Rica'] = {'n': 11 + 13/60, 's': 5 + 31/60, 'mn': 11 + 13/60, 'ms': 8 + 1/15}
x_lats['Ghana'] = {'n': 11 + 1/6, 's': 4 + 11/15, 'mn': 11 + 1/6, 'ms': 4 + 11/15}
x_lats['Togo'] = {'n': 11 + 2/15, 's': 6 + 7/60, 'mn': 11 + 2/15, 'ms': 6 + 7/60}
x_lats['Central African Republic'] = {'n': 11 + 1/60, 's': 2 + 13/60, 'mn': 11 + 1/60, 'ms': 2 + 13/60}
x_lats['Cote d\'Ivoire'] = {'n': 10 + 11/15, 's': 4 + 11/30, 'mn': 10 + 11/15, 'ms': 4 + 11/30}
x_lats['Micronesia'] = {'n': 10 + 1/12, 's': 1 + 1/60, 'mn': 10 + 1/12, 'ms': 1 + 1/60}
x_lats['Sierra Leone'] = {'n': 9 + 59/60, 's': 6 + 14/15, 'mn': 9 + 59/60, 'ms': 6 + 14/15}

x_lats['Panama'] = {'n': 9 + 19/30, 's': 7 + 11/60, 'mn': 9 + 19/30, 'ms': 7 + 11/60}
x_lats['Sri Lanka'] = {'n': 9.5, 's': 5 + 11/12, 'mn': 9.5, 'ms': 5 + 11/12}
x_lats['Liberia'] = {'n': 8 + 11/20, 's': 4 + 7/20, 'mn': 8 + 11/20, 'ms': 4 + 7/20}
x_lats['Guyana'] = {'n': 8.4, 's': 1 + 11/60, 'mn': 8.4, 'ms': 1 + 11/60}
x_lats['Palau'] = {'n': 8 + 1/6, 's': 2 + 47/60, 'mn': 8 + 1/6, 'ms': 2 + 47/60}
x_lats['Malaysia'] = {'n': 7.25, 's': 17/20, 'mn': 7.25, 'ms': 17/20}
x_lats['Maldives'] = {'n': 7 + 7/60, 's': -0.7, 'mn': 7 + 7/60, 'ms': -0.7}
x_lats['Indonesia'] = {'n': 6 + 1/15, 's': -11, 'mn': 6 + 1/15, 'ms': -11}
x_lats['Suriname'] = {'n': 6 + 1/60, 's': 1 + 5/6, 'mn': 6 + 1/60, 'ms': 1 + 5/6}
x_lats['Kenya'] = {'n': 5 + 7/12, 's': -4 - 43/60, 'mn': 5 + 7/12, 'ms': -4 - 43/60}

In [88]:
x_lats['Democratic Republic of the Congo'] = {'n': 5 + 11/30, 's': -13 - 9/20, 'mn': 5 + 11/30, 'ms': -13 - 9/20}
x_lats['Brazil'] = {'n': 5.25, 's': -33.75, 'mn': 5.25, 'ms': -33.75}
x_lats['Brunei'] = {'n': 5 + 1/15, 's': 4, 'mn': 5 + 1/15, 'ms': 4}
x_lats['Uganda'] = {'n': 4 + 7/30, 's': -1 - 29/60, 'mn': 4 + 7/30, 'ms': -1 - 29/60}
x_lats['Equatorial Guinea'] = {'n': 3 + 47/60, 's': -1 - 7/15, 'mn': 3 + 47/60, 'ms': -1 - 7/15}
x_lats['Republic of the Congo'] = {'n': 3 + 43/60, 's': -5 - 1/30, 'mn': 3 + 43/60, 'ms': -5 - 1/30}
x_lats['Kiribati'] = {'n': 3 + 23/60, 's': -11 - 13/30, 'mn': 3 + 23/60, 'ms': -11 - 13/30}
x_lats['Gabon'] = {'n': 2 + 19/60, 's': -3 - 59/60, 'mn': 2 + 19/60, 'ms': -3 - 59/60}
x_lats['Sao Tome and Principe'] = {'n': 1.7, 's': -1/60, 'mn': 1.7, 'ms': -1/60}
x_lats['Ecuador'] = {'n': 1 + 41/60, 's': -5, 'mn': 1 + 2/3, 'ms': -5}

x_lats['Singapore'] = {'n': 1 + 7/15, 's': 1 + 3/20, 'mn': 1 + 7/15, 'ms': 1 + 3/20}
x_lats['Peru'] = {'n': 1/60, 's': -18 - 7/20, 'mn': 1/60, 'ms': -18 - 7/20}
x_lats['Nauru'] = {'n': -0.5, 's': -11/20, 'mn': -0.5, 'ms': -11/20}
x_lats['Papua New Guinea'] = {'n': -13/15, 's': -11 - 23/30, 'mn': -2 - 7/12, 'ms': -10.7}
x_lats['Tanzania'] = {'n': -59/60, 's': -11.75, 'mn': -59/60, 'ms': -11.75}
x_lats['Rwanda'] = {'n': -1 - 1/20, 's': -2 - 17/20, 'mn': -1 - 1/20, 'ms': -2 - 17/20}
x_lats['Burundi'] = {'n': -2.3, 's': -4 - 7/15, 'mn': -2.3, 'ms': -4 - 7/15}
x_lats['Seychelles'] = {'n': -3 - 43/60, 's': -10 - 13/60, 'mn': -3 - 43/60, 'ms': -10 - 13/60}
x_lats['Angola'] = {'n': -4.4, 's': -18 - 1/30, 'mn': -4.4, 'ms': -18 - 1/30}
x_lats['Solomon Islands'] = {'n': -5 - 13/60, 's': -11 - 47/60, 'mn': -5 - 13/60, 'ms': -11 - 47/60}

x_lats['Tuvalu'] = {'n': -5 - 13/20, 's': -10.8, 'mn': -5 - 13/20, 'ms': -10.8}
x_lats['Zambia'] = {'n': -8.2, 's': -18 - 1/12, 'mn': -8.2, 'ms': -18 - 1/12}
x_lats['Timor-Leste'] = {'n': -8 - 7/60, 's': -9.5, 'mn': -8 - 19/60, 'ms': -9.5}
x_lats['Australia'] = {'n': -9 - 2/15, 's': -55 - 1/20, 'mn': -10 - 41/60, 'ms': -39 - 2/15}
x_lats['Malawi'] = {'n': -9 - 11/30, 's': -17 - 7/60, 'mn': -9 - 11/30, 'ms': -17 - 7/60}
x_lats['Bolivia'] = {'n': -9 - 2/3, 's': -22.9, 'mn': -9 - 2/3, 'ms': -22.9}
x_lats['Mauritius'] = {'n': -10 - 5/12, 's': -20 - 8/15, 'mn': -10 - 5/12, 'ms': -20 - 8/15}
x_lats['Mozambique'] = {'n': -10 - 9/20, 's': -26 - 13/15, 'mn': -10 - 9/20, 'ms': -26 - 13/15}
x_lats['Comoros'] = {'n': -11 - 11/30, 's': -12 - 5/12, 'mn': -11 - 11/30, 'ms': -12 - 5/12}
x_lats['Madagascar'] = {'n': -11 - 19/20, 's': -25 - 37/60, 'mn': -11 - 19/20, 'ms': -25 - 37/60}

x_lats['Fiji'] = {'n': -12.5, 's': -21 - 11/15, 'mn': -12.5, 'ms': -21 - 11/15}
x_lats['Vanuatu'] = {'n': -13 - 7/60, 's': -20.25, 'mn': -13 - 7/60, 'ms': -20.25}
x_lats['Samoa'] = {'n': -13 - 5/12, 's': -14 - 1/15, 'mn': -13 - 5/12, 'ms': -14 - 1/15}
x_lats['Tonga'] = {'n': -15.6, 's': -22 - 7/20, 'mn': -15.6, 'ms': -22 - 7/20}
x_lats['Zimbabwe'] = {'n': 15 - 37/60, 's': -22 - 5/6, 'mn': -15 - 37/60, 'ms': -22 - 5/6}
x_lats['Namibia'] = {'n': -16 - 14/15, 's': -28 - 29/30, 'mn': -16 - 14/15, 'ms': -28 - 29/30}
x_lats['Chile'] = {'n': -17 - 19/60, 's': -56 - 8/15, 'mn': -17 - 19/60, 'ms': -53 - 53/60}
x_lats['Botswana'] = {'n': -17 - 23/30, 's': -26.9, 'mn': -17 - 23/30, 'ms': -26.9}
x_lats['Paraguay'] = {'n': -19 - 17/60, 's': -27 - 43/60, 'mn': -19 - 17/60, 'ms': -27 - 43/60}
x_lats['Argentina'] = {'n': -21.8, 's': -55 - 1/15, 'mn': -21.8, 'ms': -52.4}

x_lats['South Africa'] = {'n': -22 - 1/3, 's': -46 - 59/60, 'mn': -22 - 1/3, 'ms': -34 - 5/6}
x_lats['Eswatini'] = {'n': -25 - 11/15, 's': -27 - 19/60, 'mn': -25 - 11/15, 'ms': -27 - 19/60}
x_lats['Lesotho'] = {'n': -28 - 17/30, 's': -30 - 2/3, 'mn': -28 - 17/30, 'ms': -30 - 2/3}
x_lats['New Zealand'] = {'n': -29 - 13/60, 's': -52 - 37/60, 'mn': -34 - 23/60, 'ms': -46 - 2/3}
x_lats['Uruguay'] = {'n': -30 - 1/12, 's': -35 - 1/30, 'mn': -30 - 1/12, 'ms': -34 - 29/30}
x_lats['Kosovo'] = {'n': 43 + 7/30, 's': 41 + 19/20, 'mn': 43 + 7/30, 'ms': 41 + 19/20}
x_lats['Guinea-Bissau'] = {'n': 12 + 41/60, 's': 10 + 13/20, 'mn': 12 + 41/60, 'ms': 10 + 11/12}

In [89]:
import json

with open("latitudes.json", "w") as json_file:
    json.dump(x_lats, json_file)

In [90]:
with open("latitudes.json", "r") as json_file:
    lats = json.load(json_file)

In [91]:
def c1Nc2(c1, c2, mainland=True):
    with open("latitudes.json", "r") as json_file:
        lats = json.load(json_file)
    
    if mainland:
        pt1 = lats[c1]['ms']
        pt2 = lats[c2]['mn']

    else:
        pt1 = lats[c1]['s']
        pt2 = lats[c2]['n']
        
    return pt1 > pt2

In [92]:
c1Nc2('Saudi Arabia', 'Honduras')

False

In [93]:
c1Nc2('China', 'Chad')

False

In [94]:
c1Nc2('China', 'Sudan')

False

In [95]:
lats['China']['ms'], lats['Sudan']['mn']

(20.233333333333334, 22.2)

In [96]:
lats['Chad']['mn']

23.483333333333334

### Easternmost and Westernmost Points

In [97]:
x_longs = {}

x_longs['India'] = {'e': 97 + 23/60, 'w': 68 + 1/20, 'me': 97 + 23/60, 'mw': 68 + 1/20}
x_longs['Bangladesh'] = {'e': 92 + 7/12, 'w': 88 + 1/20, 'me': 92 + 7/12, 'mw': 88 + 1/20}
x_longs['Bhutan'] = {'e': 92 + 1/12, 'w': 88.75, 'me': 92 + 1/12, 'mw': 88.75}
x_longs['Liechtenstein'] = {'e': 9 + 11/20, 'w': 9 + 7/15, 'me': 9 + 11/20, 'mw': 9 + 7/15}
x_longs['Guatemala'] = {'e': -88.25, 'w': -92.25, 'me': -88.25, 'mw': -92.25}
x_longs['Nepal'] = {'e': 88.25, 'w': 80 + 1/20, 'me': 88.25, 'mw': 80 + 1/20}
x_longs['El Salvador'] = {'e': -87.7, 'w': -90.25, 'me': -87.7, 'mw': -90.25}
x_longs['Belize'] = {'e': -87 - 7/12, 'w': -89.2, 'me': -87 - 7/12, 'mw': -89.2}
x_longs['Kazakhstan'] = {'e': 87.5, 'w': 50, 'me': 87.5, 'mw': 50}
x_longs['Mexico'] = {'e': -86.7, 'w': -118 - 11/30, 'me': -86.7, 'mw': -117 - 1/30}

x_longs['Honduras'] = {'e': -83 - 7/12, 'w': -88 - 43/60, 'me': -83 - 7/12, 'mw': -88 - 43/60}
x_longs['Nicaragua'] = {'e': -82 - 23/30, 'w': -87 - 2/3, 'me': -82 - 23/30, 'mw': -87 - 2/3}
x_longs['Costa Rica'] = {'e': -82.5, 'w': -87 - 1/12, 'me': -82.5, 'mw': -85 - 5/6}
x_longs['Sri Lanka'] = {'e': 81 + 2/3, 'w': 79 + 31/60, 'me': 81 + 2/3, 'mw': 79 + 31/60}
x_longs['Kyrgyzstan'] = {'e': 80 + 1/3, 'w': 69 + 1/3, 'me': 80 + 1/3, 'mw': 69 + 1/3}
x_longs['Pakistan'] = {'e': 77.5, 'w': 61, 'me': 77.5, 'mw': 61}
x_longs['Panama'] = {'e': -77 - 3/20, 'w': -83 - 1/15, 'me': -77 - 3/20, 'mw': -83 - 1/15}
x_longs['Jamaica'] = {'e': -76.2, 'w': -78 - 11/30, 'me': -76.2, 'mw': -78 - 11/30}
x_longs['Ecuador'] = {'e': -75.25, 'w': -92 - 1/60, 'me': -75.25, 'mw': -80 - 1/12}
x_longs['Tajikistan'] = {'e': 75 + 1/12, 'w': 67 + 5/12, 'me': 75 + 1/12, 'mw': 67 + 5/12}

x_longs['Afghanistan'] = {'e': 75, 'w': 60.5, 'me': 75, 'mw': 60.5}
x_longs['Cuba'] = {'e': -74 - 2/15, 'w': -84 - 29/30, 'me': -74 - 2/15, 'mw': -84 - 29/30}
x_longs['Maldives'] = {'e': 73 + 31/60, 'w': 72.7, 'me': 73 + 31/60, 'mw': 72.7}
x_longs['Uzbekistan'] = {'e': 73 + 1/3, 'w': 56, 'me': 73 + 1/3, 'mw': 56}
x_longs['Bahamas'] = {'e': -72.75, 'w': -79.25, 'me': -72.75, 'mw': -79.25}
x_longs['United Kingdom'] = {'e': 72.5, 'w': -130 - 11/15, 'me': 1 + 23/30, 'mw': -8 - 1/6}
x_longs['Haiti'] = {'e': -71 - 19/30, 'w': -74 - 7/15, 'me': -71 - 19/30, 'mw': -74 - 7/15}
x_longs['Guinea'] = {'e': -7.75, 'w': -15 - 1/20, 'me': -7.75, 'mw': -15 - 1/20}
x_longs['Monaco'] = {'e': 7 + 13/30, 'w': 7 + 5/12, 'me': 7 + 13/30, 'mw': 7 + 5/12}
x_longs['Liberia'] = {'e': -7 - 11/30, 'w': -11.5, 'me': -7 - 11/30, 'mw': -11.5}

x_longs['Netherlands'] = {'e': 7 + 13/60, 'w': -70 - 1/60, 'me': 7 + 13/60, 'mw': 3 + 7/20}
x_longs['Peru'] = {'e': -68 - 13/20, 'w': -81 - 1/3, 'me': -68 - 13/20, 'mw': -81 - 1/3}
x_longs['Dominican Republic'] = {'e': -68 - 1/3, 'w': -72, 'me': -68 - 1/3, 'mw': -72}
x_longs['Colombia'] = {'e': -67, 'w': -81 - 11/15, 'me': -67, 'mw': -79}
x_longs['Turkmenistan'] = {'e': -66 - 2/3, 'w': 52 + 5/12, 'me': -66 - 2/3, 'mw': 52 + 5/12}
x_longs['Chile'] = {'e': -66.4, 'w': -109 - 9/20, 'me': -66 - 29/30, 'mw': -75- 19/30}
x_longs['United States'] = {'e': 179 + 23/30, 'w': 172 + 13/30, 'me': -66 - 14/15, 'mw': 172 + 13/30}
x_longs['Mauritius'] = {'e': 63.5, 'w': 56 + 7/12, 'me': 63.5, 'mw': 56 + 7/12}
x_longs['Iran'] = {'e': 63.3, 'w': 44 + 1/20, 'me': 63.3, 'mw': 44 + 1/20}
x_longs['Saint Kitts and Nevis'] = {'e': -62 - 31/60, 'w': -62 - 17/20, 'me': -62 - 31/60, 'mw': -62 - 17/20}

x_longs['Antigua and Barbuda'] = {'e': -61 - 2/3, 'w': -61 - 11/12, 'me': -61 - 2/3, 'mw': -61 - 11/12}
x_longs['Grenada'] = {'e': -61 - 23/60, 'w': -61.8, 'me': -61 - 23/60, 'mw': -61.8}
x_longs['Dominica'] = {'e': -61.25, 'w': -61.5, 'me': -61.25, 'mw': -61.5}
x_longs['Saint Vincent and the Grenadines'] = {'e': -61 - 2/15, 'w': -61 - 13/30, 'me': -61 - 2/15, 'mw': -61 - 13/30}
x_longs['Saint Lucia'] = {'e': -60.9, 'w': -61 - 1/15, 'me': -60.9, 'mw': -61 - 1/15}
x_longs['Trinidad and Tobago'] = {'e': -60 - 31/60, 'w': -61 - 14/15, 'me': -60 - 31/60, 'mw': -61 - 14/15}
x_longs['Luxembourg'] = {'e': 6 + 8/15, 'w': 5 + 11/15, 'me': 6 + 8/15, 'mw': 5 + 11/15}
x_longs['Belgium'] = {'e': 6 + 11/30, 'w': 2 + 7/12, 'me': 6 + 11/30, 'mw': 2 + 7/12}
x_longs['Portugal'] = {'e': -6 - 11/60, 'w': -31 - 4/15, 'me': -6 - 11/60, 'mw': -9 - 5/6}
x_longs['Oman'] = {'e': 59 + 5/6, 'w': 52, 'me': 59 + 5/6, 'mw': 52}

In [98]:
x_longs['Venezuela'] = {'e': -59.75, 'w': -73 - 1/3, 'me': -59.75, 'mw': -73 - 1/3}
x_longs['Barbados'] = {'e': -59 - 13/30, 'w': -59 - 2/3, 'me': -59 - 13/30, 'mw': -59 - 2/3}
x_longs['Bolivia'] = {'e': -57 - 9/20, 'w': -69 - 2/3, 'me': -57 - 9/20, 'mw': -69 - 2/3}
x_longs['Guyana'] = {'e': -56.5, 'w': -61 - 5/12, 'me': -56.5, 'mw': -61 - 5/12}
x_longs['United Arab Emirates'] = {'e': 56.4, 'w': 51 + 11/20, 'me': 56.4, 'mw': 51 + 11/20}
x_longs['Seychelles'] = {'e': 56 + 4/15, 'w': 46 + 29/60, 'me': 56 + 4/15, 'mw': 46 + 29/60}
x_longs['France'] = {'e': 172.1, 'w': -154 - 13/15, 'me': 8 + 13/60, 'mw': -4 - 47/60}
x_longs['Saudi Arabia'] = {'e': 55.5, 'w': 34 + 11/20, 'me': 55.5, 'mw': 34 + 5/6}
x_longs['Yemen'] = {'e': 54.5, 'w': 41 + 49/60, 'me': 53 + 1/6, 'mw': 41 + 49/60}
x_longs['Paraguay'] = {'e': -54.25, 'w': -62 - 7/12, 'me': -54.25, 'mw': -62 - 7/12}

x_longs['Suriname'] = {'e': -54, 'w': -58 - 1/12, 'me': -54, 'mw': -58 - 1/12}
x_longs['Uruguay'] = {'e': -53 - 1/12, 'w': -58 - 5/12, 'me': -53 - 1/12, 'mw': -58 - 5/12}
x_longs['Argentina'] = {'e': -53 - 41/60, 'w': -73.5, 'me': -53 - 41/60, 'mw': -73.5}
x_longs['Canada'] = {'e': -52 - 37/60, 'w': -141, 'me': -55 - 37/60, 'mw': -141}
x_longs['Qatar'] = {'e': 51 + 13/20, 'w': 50.75, 'me': 51 + 13/20, 'mw': 50.75}
x_longs['Somalia'] = {'e': 51 + 9/20, 'w': 41, 'me': 51 + 9/20, 'mw': 41}
x_longs['Bahrain'] = {'e': 50 + 43/60, 'w': 50 + 23/60, 'me': 50 + 43/60, 'mw': 50 + 23/60}
x_longs['Madagascar'] = {'e': 50 + 2/3, 'w': 43.5, 'me': 50 + 2/3, 'mw': 43.5}
x_longs['Azerbaijan'] = {'e': 50 + 11/20, 'w': 44 + 23/30, 'me': 50 + 11/20, 'mw': 44 + 23/30}
x_longs['Ireland'] = {'e': -5 - 59/60, 'w': -10 - 2/3, 'me': -5 - 59/60, 'mw': -10 - 7/15}

x_longs['Kuwait'] = {'e': 48 + 2/3, 'w': 46 + 17/30, 'me': 48 + 2/3, 'mw': 46 + 17/30}
x_longs['Iraq'] = {'e': 48 + 8/15, 'w': 38 + 5/6, 'me': 48 + 8/15, 'mw': 38 + 5/6}
x_longs['Ethiopia'] = {'e': 48, 'w': 33, 'me': 48, 'mw': 33}
x_longs['Georgia'] = {'e': 46 + 2/3, 'w': 41.5, 'me': 46 + 2/3, 'mw': 41.5}
x_longs['Armenia'] = {'e': 46 + 37/60, 'w': 43 + 9/20, 'me': 46 + 37/60, 'mw': 43 + 9/20}
x_longs['Turkiye'] = {'e': 44 + 49/60, 'w': 25 + 2/3, 'me': 44 + 49/60, 'mw': 26 + 1/20}
x_longs['Comoros'] = {'e': 44 + 8/15, 'w': 43.2, 'me': 44 + 8/15, 'mw': 43.2}
x_longs['Eritrea'] = {'e': 43 + 7/60, 'w': 36 + 5/6, 'me': 43 + 7/60, 'mw': 36 + 5/6}
x_longs['Djibouti'] = {'e': 43 + 5/12, 'w': 41 + 23/30, 'me': 43 + 5/12, 'mw': 41 + 23/30}
x_longs['Syria'] = {'e': 42 + 5/12, 'w': 35.5, 'me': 42 + 5/12, 'mw': 35.5}

x_longs['Kenya'] = {'e': 41, 'w': 35, 'me': 41, 'mw': 35}
x_longs['Mozambique'] = {'e': 40.75, 'w': 30.25, 'me': 40.75, 'mw': 30.25}
x_longs['Tanzania'] = {'e': 40 + 29/60, 'w': 29 + 1/6, 'me': 40 + 29/60, 'mw': 29 + 1/6}
x_longs['Ukraine'] = {'e': 40.25, 'w': 22.25, 'me': 40.25, 'mw': 22.25}
x_longs['Mauritania'] = {'e': -4.75, 'w': -17 - 1/20, 'me': -4.75, 'mw': -17 - 1/20}
x_longs['Spain'] = {'e': 4 + 19/60, 'w': -18 - 3/20, 'me': 3 + 19/60, 'mw': -18 - 3/20}
x_longs['Mali'] = {'e': 4, 'w': -12, 'me': 4, 'mw': -12}
x_longs['Jordan'] = {'e': 39 + 1/3, 'w': 34 + 11/12, 'me': 39 + 1/3, 'mw': 34 + 11/12}
x_longs['Sudan'] = {'e': 38 + 7/12, 'w': 21 + 5/6, 'me': 38 + 7/12, 'mw': 21 + 5/6}
x_longs['South Africa'] = {'e': 38, 'w': 16.5, 'me': 32 + 53/60, 'mw': 16.5}

x_longs['Lebanon'] = {'e': 36 + 19/30, 'w': 35.1, 'me': 36 + 19/30, 'mw': 35.1}
x_longs['Malawi'] = {'e': 35 + 11/12, 'w': 32 + 2/3, 'me': 35 + 11/12, 'mw': 32 + 2/3}
x_longs['South Sudan'] = {'e': 35.8, 'w': 23 + 23/60, 'me': 35.8, 'mw': 23 + 23/60}
x_longs['Egypt'] = {'e': 35.75, 'w': 24 + 2/3, 'me': 35.75, 'mw': 24 + 2/3}
x_longs['Israel'] = {'e': 35 + 2/3, 'w': 34.25, 'me': 35 + 2/3, 'mw': 34.25}
x_longs['Uganda'] = {'e': 35 + 1/30, 'w': 29 + 17/30, 'me': 35 + 1/30, 'mw': 29 + 17/30}
x_longs['Cyprus'] = {'e': 34.6, 'w': 32 + 4/15, 'me': 34.6, 'mw': 32 + 4/15}
x_longs['Norway'] = {'e': 33.5, 'w': -9 - 1/12, 'me': 31 + 1/60, 'mw': 4 + 14/15}
x_longs['Zimbabwe'] = {'e': 33, 'w': 25 + 1/3, 'me': 33, 'mw': 25 + 1/3}
x_longs['Zambia'] = {'e': 32 + 5/6, 'w': 22, 'me': 32 + 5/6, 'mw': 22}

In [99]:
x_longs['Belarus'] = {'e': 32 + 23/30, 'w': 23 + 1/6, 'me': 32 + 23/30, 'mw': 23 + 1/6}
x_longs['Finland'] = {'e': 31 + 7/12, 'w': 19 + 13/60, 'me': 31 + 7/12, 'mw': 20 + 8/15}
x_longs['Rwanda'] = {'e': 30 + 53/60, 'w': 28 + 13/15, 'me': 30 + 53/60, 'mw': 28 + 13/15}
x_longs['Burundi'] = {'e': 30 + 5/6, 'w': 28 + 59/60, 'me': 30 + 5/6, 'mw': 28 + 59/60}
x_longs['Moldova'] = {'e': 30 + 1/6, 'w': 26 + 2/3, 'me': 30 + 1/6, 'mw': 26 + 2/3}
x_longs['Benin'] = {'e': 3 + 5/6, 'w': 5/6, 'me': 3 + 5/6, 'mw': 5/6}
x_longs['Romania'] = {'e': 29 + 2/3, 'w': 20 + 19/60, 'me': 29 + 2/3, 'mw': 20 + 19/60}
x_longs['Greece'] = {'e': 29 + 19/30, 'w': 19 + 23/60, 'me': 26 + 19/30, 'mw': 19 + 59/60}
x_longs['Lesotho'] = {'e': 29 + 7/15, 'w': 27, 'me': 29 + 7/15, 'mw': 27}
x_longs['Botswana'] = {'e': 29 + 1/3, 'w': 20, 'me': 29 + 1/3, 'mw': 20}

x_longs['Brazil'] = {'e': -28 - 5/6, 'w': -73 - 59/60, 'me': -34 - 47/60, 'mw': -73 - 59/60}
x_longs['Bulgaria'] = {'e': 28.6, 'w': 22 + 7/20, 'me': 28.6, 'mw': 22 + 7/20}
x_longs['Latvia'] = {'e': 28.25, 'w': 21, 'me': 28.25, 'mw': 21}
x_longs['Estonia'] = {'e': 28.2, 'w': 21 + 23/30, 'me': 28.2, 'mw': 23.4}
x_longs['Central African Republic'] = {'e': 27 + 7/15, 'w': 14 + 1/3, 'me': 27 + 7/15, 'mw': 14 + 1/3}
x_longs['Lithuania'] = {'e': 26 + 5/6, 'w': 20 + 29/30, 'me': 26 + 5/6, 'mw': 20 + 29/30}
x_longs['Namibia'] = {'e': 25.25, 'w': 11.75, 'me': 25.25, 'mw': 11.75}
x_longs['Libya'] = {'e': 25 + 1/12, 'w': 9 + 1/3, 'me': 25 + 1/12, 'mw': 9 + 1/3}
x_longs['Sweden'] = {'e': 24 + 1/6, 'w': 10 + 19/20, 'me': 24.25, 'mw': 10 + 19/20}
x_longs['Poland'] = {'e': 24 + 3/20, 'w': 14 + 7/60, 'me': 24 + 3/20, 'mw': 14 + 7/60}

x_longs['Angola'] = {'e': 24, 'w': 11 + 2/3, 'me': 24, 'mw': 11 + 2/3}
x_longs['Chad'] = {'e': 24, 'w': 13 + 2/3, 'me': 24, 'mw': 13 + 2/3}
x_longs['Serbia'] = {'e': 23 + 1/60, 'w': 18 + 17/20, 'me': 23 + 1/60, 'mw': 18 + 17/20}
x_longs['North Macedonia'] = {'e': 23, 'w': 20.5, 'me': 23, 'mw': 20.5}
x_longs['Hungary'] = {'e': 22 + 11/12, 'w': 16 + 2/15, 'me': 22 + 11/12, 'mw': 16 + 2/15}
x_longs['Cabo Verde'] = {'e': -22 - 2/3, 'w': -25 - 5/12, 'me': -22 - 2/3, 'mw': -25 - 5/12}
x_longs['Slovakia'] = {'e': 22.5, 'w': 16 + 5/6, 'me': 22.5, 'mw': 16 + 5/6}
x_longs['Albania'] = {'e': 21 + 1/15, 'w': 19 + 17/60, 'me': 21 + 1/15, 'mw': 19 + 17/60}
x_longs['Montenegro'] = {'e': 20 + 7/20, 'w': 18 + 13/30, 'me': 20 + 7/20, 'mw': 18 + 13/30}
x_longs['Burkina Faso'] = {'e': 2 + 5/12, 'w': -5.5, 'me': 2 + 5/12, 'mw': -5.5}

x_longs['Bosnia and Herzegovina'] = {'e': 19.5, 'w': 15 + 5/6, 'me': 19.5, 'mw': 15 + 5/6}
x_longs['Croatia'] = {'e': 19 + 9/20, 'w': 13.5, 'me': 19 + 9/20, 'mw': 13.5}
x_longs['Czechia'] = {'e': 18 + 17/20, 'w': 12 + 1/12, 'me': 18 + 17/20, 'mw': 12 + 1/12}
x_longs['Republic of the Congo'] = {'e': 18 + 2/3, 'w': 11 + 1/6, 'me': 18 + 2/3, 'mw': 11 + 1/6}
x_longs['Italy'] = {'e': 18 + 31/60, 'w': 6 + 37/60, 'me': 18 + 31/60, 'mw': 6 + 37/60}
x_longs['Tuvalu'] = {'e': 179 + 17/20, 'w': 176 + 1/20, 'me': 179 + 17/20, 'mw': 176 + 1/20}
x_longs['Fiji'] = {'e': -178.25, 'w': 176 + 53/60, 'me': -178.25, 'mw': 176 + 53/60}
x_longs['New Zealand'] = {'e': -175.75, 'w': 166.7, 'me': -175.75, 'mw': 166.7}
x_longs['Tonga'] = {'e': -173 - 43/60, 'w': -175 - 19/30, 'me': -173 - 43/60, 'mw': -175 - 19/30}
x_longs['Marshall Islands'] = {'e': 172 + 3/20, 'w': 160.9, 'me': 172 + 3/20, 'mw': 160.9}

x_longs['Samoa'] = {'e': -171 - 1/3, 'w': -172.8, 'me': -171 - 1/3, 'mw': -172.8}
x_longs['Vanuatu'] = {'e': 170 + 13/60, 'w': 166 + 11/20, 'me': 170 + 13/60, 'mw': 166 + 11/20}
x_longs['Solomon Islands'] = {'e': 170 + 1/6, 'w': 155 + 11/20, 'me': 170 + 1/6, 'mw': 155 + 11/20}
x_longs['Austria'] = {'e': 17 + 3/20, 'w': 9 + 8/15, 'me': 17 + 3/20, 'mw': 9 + 8/15}
x_longs['Russia'] = {'e': 180, 'w': 19 + 19/30, 'me': 180, 'mw': 19 + 19/30}
x_longs['Australia'] = {'e': 167 + 19/20, 'w': 72 + 7/12, 'me': 153 + 19/30, 'mw': 113 + 3/20}
x_longs['Nauru'] = {'e': 166 + 19/20, 'w': 166 + 53/60, 'me': 166 + 19/20, 'mw': 166 + 53/60}
x_longs['Slovenia'] = {'e': 16.6, 'w': 13 + 23/60, 'me': 16.6, 'mw': 13 + 23/60}
x_longs['Cameroon'] = {'e': 16.2, 'w': 8.75, 'me': 16.2, 'mw': 8.75}
x_longs['Niger'] = {'e': 16, 'w': 7/60, 'me': 16, 'mw': 7/60}

In [100]:
x_longs['Papua New Guinea'] = {'e': 159.4, 'w': 140 + 11/12, 'me': 150 + 13/15, 'mw': 140 + 11/12}
x_longs['Japan'] = {'e': 153 + 59/60, 'w': 122 + 14/15, 'me': 145 + 49/60, 'mw': 129 + 43/60}
x_longs['Kiribati'] = {'e': -150 - 13/60, 'w': 169 + 8/15, 'me': -150 - 13/60, 'mw': 169 + 8/15}
x_longs['Germany'] = {'e': 15 + 1/30, 'w': 5 + 53/60, 'me': 15 + 1/30, 'mw': 5 + 53/60}
x_longs['Denmark'] = {'e': 15 + 11/60, 'w': -73 - 7/30, 'me': 15 + 11/60, 'mw': 8 + 1/12}
x_longs['Indonesia'] = {'e': 141 + 1/12, 'w': 94.75, 'me': 141 + 1/12, 'mw': 94.75}
x_longs['Malta'] = {'e': 14 + 17/30, 'w': 14.2, 'me': 14 + 17/30, 'mw': 14.2}
x_longs['Gabon'] = {'e': 14.5, 'w': 8.7, 'me': 14.5, 'mw': 8.7}
x_longs['China'] = {'e': 134 + 23/30, 'w': 73 + 11/20, 'me': 134 + 23/30, 'mw': 73 + 11/20}
x_longs['Palau'] = {'e': 134.7, 'w': 131 + 7/60, 'me': 134.7, 'mw': 131 + 7/60}

x_longs['South Korea'] = {'e': 130 + 14/15, 'w': 124 + 13/20, 'me': 129 + 7/12, 'mw': 124 + 13/20}
x_longs['North Korea'] = {'e': 130 + 2/3, 'w': 124 + 1/6, 'me': 130 + 2/3, 'mw': 124 + 1/6}
x_longs['Gambia'] = {'e': -13 - 4/5, 'w': -16.75, 'me': -13 - 4/5, 'mw': -16.75}
x_longs['Guinea-Bissau'] = {'e': -13 - 2/3, 'w': -16.7, 'me': -13 - 2/3, 'mw': -16.7}
x_longs['Nigeria'] = {'e': 13.25, 'w': 2.75, 'me': 13.25, 'mw': 2.75}
x_longs['Iceland'] = {'e': -13 - 7/30, 'w': -24 - 8/15, 'me': -13 - 7/30, 'mw': -24 - 8/15}
x_longs['Philippines'] = {'e': 126 + 17/30, 'w': 114 + 17/60, 'me': 126 + 17/30, 'mw': 114 + 17/60}
x_longs['Taiwan'] = {'e': 122.1, 'w': 118 + 7/30, 'me': 122.1, 'mw': 118 + 7/30}
x_longs['San Marino'] = {'e': 12 + 31/60, 'w': 12.4, 'me': 12 + 31/60, 'mw': 12.4}
x_longs['Vatican City'] = {'e': 12 + 9/20, 'w': 12 + 9/20, 'me': 12 + 9/20, 'mw': 12 + 9/20}

x_longs['Algeria'] = {'e': 12, 'w': -8 - 2/3, 'me': 12, 'mw': -8 - 2/3}
x_longs['Mongolia'] = {'e': 119 + 14/15, 'w': 88, 'me': 119 + 14/15, 'mw': 88}
x_longs['Malaysia'] = {'e': 119 + 1/6, 'w': 99 + 37/60, 'me': 119 + 1/6, 'mw': 99 + 37/60}
x_longs['Brunei'] = {'e': 115 + 5/12, 'w': 114 + 1/12, 'me': 115 + 5/12, 'mw': 114 + 1/12}
x_longs['Tunisia'] = {'e': 11 + 7/12, 'w': 7 + 7/12, 'me': 11 + 7/12, 'mw': 7 + 7/12}
x_longs['Senegal'] = {'e': -11 - 11/30, 'w': -17 - 9/20, 'me': -11 - 11/30, 'mw': -17 - 9/20}
x_longs['Equatorial Guinea'] = {'e': 11 + 1/3, 'w': 5 + 37/60, 'me': 11 + 1/3, 'mw': 5 + 37/60}
x_longs['Vietnam'] = {'e': 109.5, 'w': 102 + 2/15, 'me': 109.5, 'mw': 102 + 2/15}
x_longs['Cambodia'] = {'e': 107 + 7/12, 'w': 102 + 5/12, 'me': 107 + 7/12, 'mw': 102 + 5/12}
x_longs['Laos'] = {'e': 106 + 2/3, 'w': 100 + 2/15, 'me': 106 + 2/3, 'mw': 100 + 2/15}

x_longs['Thailand'] = {'e': 105 + 2/3, 'w': 97 + 1/3, 'me': 105 + 2/3, 'mw': 97 + 1/3}
x_longs['Singapore'] = {'e': 104.4, 'w': 103.6, 'me': 104.4, 'mw': 103.6}
x_longs['Myanmar'] = {'e': 101 + 1/6, 'w': 92.25, 'me': 101 + 1/6, 'mw': 92.25}
x_longs['Switzerland'] = {'e': 10 + 29/60, 'w': 5 + 19/20, 'me': 10 + 29/60, 'mw': 5 + 19/20}
x_longs['Sierra Leone'] = {'e': -10 - 17/60, 'w': -13.3, 'me': -10 - 17/60, 'mw': -13.3}
x_longs['Andorra'] = {'e': 1 + 47/60, 'w': 1 + 5/12, 'me': 1 + 47/60, 'mw': 1 + 5/12}
x_longs['Togo'] = {'e': 1 + 23/30, 'w': -3/20, 'me': 1 + 23/30, 'mw': -3/20}
x_longs['Morocco'] = {'e': -1 - 1/6, 'w': -13.25, 'me': -1 - 1/6, 'mw': -13.25}
x_longs['Ghana'] = {'e': 1 + 1/6, 'w': -3.25, 'me': 1 + 1/6, 'mw': -3.25}
x_longs['Cote d\'Ivoire'] = {'e': -2.5, 'w': -8 - 7/12, 'me': -2.5, 'mw': -8 - 7/12}

x_longs['Democratic Republic of the Congo'] = {'e': 31 + 19/60, 'w': 12 + 1/3, 'me': 31 + 19/60, 'mw': 12 + 1/3}
x_longs['Eswatini'] = {'e': 32 + 2/15, 'w': 30.8, 'me': 32 + 2/15, 'mw': 30.8}
x_longs['Kosovo'] = {'e': 21 + 11/15, 'w': 20 + 1/20, 'me': 21 + 11/15, 'mw': 20 + 1/20}
x_longs['Micronesia'] = {'e': 163, 'w': 137.5, 'me': 163, 'mw': 137.5}
x_longs['Palestine'] = {'e': 35.3, 'w': 34 + 13/60, 'me': 35.3, 'mw': 34 + 13/60}
x_longs['Sao Tome and Principe'] = {'e': 7 + 7/15, 'w': 6 + 11/20, 'me': 7 + 7/15, 'mw': 6 + 11/20}
x_longs['Timor-Leste'] = {'e': 127 + 7/20, 'w': 124, 'me': 127 + 7/20, 'mw': 124}

In [101]:
x_lats.keys() == x_longs.keys()

True

In [104]:
import copy

x_pts = {}

x_lats2 = copy.deepcopy(x_lats)
x_longs2 = copy.deepcopy(x_longs)

In [105]:
x_lats2['Togo'].update(x_longs2['Togo'])

In [106]:
x_lats2['Togo']

{'n': 11.133333333333333,
 's': 6.116666666666666,
 'mn': 11.133333333333333,
 'ms': 6.116666666666666,
 'e': 1.7666666666666666,
 'w': -0.15,
 'me': 1.7666666666666666,
 'mw': -0.15}

In [107]:
x_lats['Togo']

{'n': 11.133333333333333,
 's': 6.116666666666666,
 'mn': 11.133333333333333,
 'ms': 6.116666666666666}

In [108]:
for k in x_lats2.keys():
    x_lats2[k].update(x_longs2[k])

In [111]:
x_lats2['Ghana']

{'n': 11.166666666666666,
 's': 4.733333333333333,
 'mn': 11.166666666666666,
 'ms': 4.733333333333333,
 'e': 1.1666666666666667,
 'w': -3.25,
 'me': 1.1666666666666667,
 'mw': -3.25}

In [112]:
with open("extreme_points.json", "w") as json_file:
    json.dump(x_lats2, json_file)

In [113]:
def c1Cc2(c1, c2, north_or_east='north', mainland=True):
    with open("extreme_points.json", "r") as json_file:
        points = json.load(json_file)
    
    if north_or_east == 'north':
    
        if mainland:
            pt1 = points[c1]['ms']
            pt2 = points[c2]['mn']

        else:
            pt1 = points[c1]['s']
            pt2 = points[c2]['n']
    
    else:
        
        if mainland:
            pt1 = points[c1]['mw']
            pt2 = points[c2]['me']
        
        else:
            pt1 = points[c1]['w']
            pt2 = points[c2]['e']
        
    return pt1 > pt2

In [119]:
ukr = x_lats2['Ukraine']

for k in x_lats2.keys():
    if (x_lats2[k]['me'] < ukr['me'] and x_lats2[k]['me'] > ukr['mw']) \
    or (x_lats2[k]['mw'] > ukr['mw'] and x_lats2[k]['mw'] < ukr['me']):
        print(k)

Norway
Finland
Sweden
Estonia
Latvia
Lithuania
Belarus
Poland
Slovakia
Hungary
Moldova
Romania
Serbia
Bulgaria
North Macedonia
Turkiye
Greece
Iraq
Syria
Cyprus
Lebanon
Jordan
Israel
Libya
Palestine
Saudi Arabia
Egypt
Chad
Sudan
Eritrea
Ethiopia
South Sudan
Central African Republic
Kenya
Democratic Republic of the Congo
Uganda
Tanzania
Rwanda
Burundi
Angola
Zambia
Malawi
Mozambique
Zimbabwe
Namibia
Botswana
South Africa
Eswatini
Lesotho

In [120]:
def mainland_overlappers(country, long=True):

    cty = x_lats2[country]
    
    out = []

    if long:
        for k in x_lats2.keys():
            if (x_lats2[k]['me'] < cty['me'] and x_lats2[k]['me'] > cty['mw']) \
            or (x_lats2[k]['mw'] > cty['mw'] and x_lats2[k]['mw'] < cty['me']):
                out.append(k)
    
    else:
        for k in x_lats2.keys():
            if (x_lats2[k]['mn'] < cty['mn'] and x_lats2[k]['mn'] > cty['ms']) \
            or (x_lats2[k]['ms'] > cty['ms'] and x_lats[k]['ms'] < cty['mn']):
                out.append(k)
    
    return out

In [121]:
mainland_overlappers('Ukraine')

['Norway',
 'Finland',
 'Sweden',
 'Estonia',
 'Latvia',
 'Lithuania',
 'Belarus',
 'Poland',
 'Slovakia',
 'Hungary',
 'Moldova',
 'Romania',
 'Serbia',
 'Bulgaria',
 'North Macedonia',
 'Turkiye',
 'Greece',
 'Iraq',
 'Syria',
 'Cyprus',
 'Lebanon',
 'Jordan',
 'Israel',
 'Libya',
 'Palestine',
 'Saudi Arabia',
 'Egypt',
 'Chad',
 'Sudan',
 'Eritrea',
 'Ethiopia',
 'South Sudan',
 'Central African Republic',
 'Kenya',
 'Democratic Republic of the Congo',
 'Uganda',
 'Tanzania',
 'Rwanda',
 'Burundi',
 'Angola',
 'Zambia',
 'Malawi',
 'Mozambique',
 'Zimbabwe',
 'Namibia',
 'Botswana',
 'South Africa',
 'Eswatini',
 'Lesotho']

In [122]:
mainland_overlappers('Fiji')

[]

In [123]:
mainland_overlappers('Australia')

['China',
 'Mongolia',
 'Japan',
 'North Korea',
 'South Korea',
 'Taiwan',
 'Philippines',
 'Micronesia',
 'Palau',
 'Malaysia',
 'Indonesia',
 'Brunei',
 'Papua New Guinea',
 'Timor-Leste']

In [127]:
mainland_overlappers('India')

['Kazakhstan',
 'China',
 'Mongolia',
 'Uzbekistan',
 'Kyrgyzstan',
 'Tajikistan',
 'Afghanistan',
 'Pakistan',
 'Nepal',
 'Myanmar',
 'Bhutan',
 'Bangladesh',
 'Thailand',
 'Sri Lanka',
 'Maldives',
 'Indonesia']

In [128]:
mainland_overlappers('Chile', long=False)

['Brazil',
 'Peru',
 'Angola',
 'Zambia',
 'Australia',
 'Bolivia',
 'Mauritius',
 'Mozambique',
 'Madagascar',
 'Fiji',
 'Vanuatu',
 'Tonga',
 'Zimbabwe',
 'Namibia',
 'Botswana',
 'Paraguay',
 'Argentina',
 'South Africa',
 'Eswatini',
 'Lesotho',
 'New Zealand',
 'Uruguay']